// apps/next/components/Grid.tsx
"use client";

import { useEffect, useState } from "react";

function getGridColumns(): number {
  const computed = getComputedStyle(document.documentElement);
  const columns = Number(computed.getPropertyValue("--columns"));

  return Number.isFinite(columns) && columns > 0 ? columns : 12;
}

export default function Grid() {
  const [columns, setColumns] = useState(() => Array.from({ length: 12 }));
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const handleResize = () => {
      setColumns(Array.from({ length: getGridColumns() }));
    };

    const frame = requestAnimationFrame(() => {
      handleResize();

      const grid = localStorage.getItem("grid");
      if (grid) setVisible(grid === "true");
    });

    window.addEventListener("resize", handleResize);

    return () => {
      cancelAnimationFrame(frame);
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (!event.shiftKey || event.key.toLowerCase() !== "g") return;

      setVisible((current) => {
        const next = !current;
        localStorage.setItem("grid", String(next));
        return next;
      });
    };

    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, []);

  if (!visible) return null;

  return (
    <div className="pointer-events-none fixed top-0 left-0 z-10 flex h-screen w-screen justify-between gap-(--gutter) px-gx">
      {columns.map((_, index) => (
        <div className="grow bg-red-500 opacity-10" key={index} />
      ))}
    </div>
  );
}

// apps/solid/src/components/Grid.tsx
import { createEffect, createSignal, onCleanup, onMount } from "solid-js";
import { isServer } from "solid-js/web";

function getGridValues() {
  const computed = getComputedStyle(document.documentElement);
  const gx = computed.getPropertyValue("--gx");
  const gutter = computed.getPropertyValue("--gutter");
  const columns = computed.getPropertyValue("--columns");

  return { gx, gutter, columns };
}

export default function Grid({}) {
  const [num, setNum] = createSignal(Array.from({ length: 12 }));

  const handleResize = () => {
    const { columns } = getGridValues(); // gx, gutter,
    setNum(Array.from({ length: +columns }));
  };

  onMount(() => {
    handleResize();
    if (!isServer) window.addEventListener("resize", handleResize);

    // get from localstorage
    const grid = localStorage.getItem("grid");
    if (grid) setVisible(grid === "true");
  });

  onCleanup(() => {
    if (!isServer) window.removeEventListener("resize", handleResize);
  });

  const [visible, setVisible] = createSignal(false);

  const handleKeyDown = (e: KeyboardEvent) => {
    if (!e.shiftKey) return;

    if (e.key === "G") {
      setVisible(!visible());
      localStorage.setItem("grid", visible().toString());
    }
  };

  createEffect(() => {
    document.addEventListener("keydown", handleKeyDown);
  });

  const styles =
    "gap-[var(--gutter)] fixed pointer-events-none left-0 top-0 z-10 flex h-[100vh] justify-between px-gx ";

  return (
    <div
      class={visible() ? styles : "invisible"}
      style="width: calc(100vw - var(--scrollbar-w, 0px))"
    >
      {num().map((item) => {
        return <div class="grow bg-red-500 opacity-10"></div>;
      })}
    </div>
  );
}
