// apps/next/components/Nav.tsx
import MobileMenu from "@/components/MobileMenu";
import RollingText from "@/components/RollingText";
import TransitionLink from "@/components/TransitionLink";

const NAV_LINKS = [
  {
    href: "/_/about",
    text: "About Us",
  },
  {
    href: "/_/animation",
    text: "Animation",
  },
  {
    href: "/_/components",
    text: "Components",
  },
  {
    href: "/_/webgl",
    text: "WebGl",
  },
  {
    href: "/_/data-loading",
    text: "Data",
  },
  {
    href: "/_/content",
    text: "CMS Content",
  },
];

export default function Nav() {
  return (
    <nav className="pointer-events-none fixed top-0 left-0 z-[100] flex w-screen items-center justify-between px-gx py-6">
      <TransitionLink
        aria-label="homepage"
        className="pointer-events-auto z-20"
        href="/"
      >
        <p>LOGO</p>
      </TransitionLink>

      <ul className="pointer-events-auto hidden justify-between md:flex">
        {NAV_LINKS.map(({ href, text }) => (
          <li key={href}>
            <TransitionLink href={href}>
              <RollingText className="px-3">{text}</RollingText>
            </TransitionLink>
          </li>
        ))}
      </ul>

      <MobileMenu>
        <ul className="flex flex-col gap-4">
          {NAV_LINKS.map(({ href, text }) => (
            <li key={href}>
              <TransitionLink href={href}>{text}</TransitionLink>
            </li>
          ))}
        </ul>
      </MobileMenu>
    </nav>
  );
}

// apps/web/src/components/Nav.jsx
import Aa from "./Aa";
import { For } from "solid-js";

// import SocialSprite from "~/components/svg/socialSprite.svg?component-solid";
import { RollingText } from "./animation/RollingText";
import MobileMenu from "./MobileMenu";

const NAV_LINKS = [
  // {
  //   to: "/",
  //   text: "Index",
  // },
  {
    to: "/about",
    text: "About",
  },
  {
    to: "/animation",
    text: "Animation",
  },
  {
    to: "/components",
    text: "Components",
  },
  {
    to: "/webgl",
    text: "WebGl",
  },
  {
    to: "/data-loading",
    text: "Data",
  },
  // {
  //   to: "/protected",
  //   text: "Protected",
  // },
];

export const Nav = () => {
  return (
    <nav class="px-gx fixed top-0 left-0 z-100 flex w-screen items-center justify-between py-6">
      <Aa to="/">
        <p>LOGO</p>
      </Aa>

      {/* desktop menu */}
      <ul class="hidden justify-between md:flex">
        <For each={NAV_LINKS}>
          {({ to, text }) => (
            <li>
              <Aa to={to}>
                <RollingText class="px-3">{text}</RollingText>
              </Aa>
            </li>
          )}
        </For>
      </ul>

      {/* mobile menu */}
      <MobileMenu>
        <ul>
          <For each={NAV_LINKS}>{({ to, text }) => <li>{text}</li>}</For>
        </ul>
      </MobileMenu>
    </nav>
  );
};
