// apps/solid/src/components/Nav.tsx
import { A } from "@solidjs/router";
import { For } from "solid-js";
import { RollingText } from "./animation/RollingText";
import MobileMenu from "./MobileMenu";
import Icon from "./icons/Icon";

const NAV_LINKS = [
  {
    to: "/_/about",
    text: "About Us",
  },
  {
    to: "/_/animation",
    text: "Animation",
  },
  {
    to: "/_/components",
    text: "Components",
  },
  {
    to: "/_/webgl",
    text: "WebGl",
  },
  {
    to: "/_/data-loading",
    text: "Data",
  },
  {
    to: "/_/content",
    text: "CMS Content",
  },
];

export const Nav = () => {
  return (
    <nav
      class="flex fixed top-0 left-0 justify-between items-center py-6 pointer-events-none px-gx z-100"
      style="width: calc(100vw - var(--scrollbar-w, 0px))"
    >
      <A
        aria-label="homepage"
        class="z-20 pointer-events-auto"
        href="/"
      >
        <p>LOGO</p>
      </A>

      {/* desktop menu */}
      <ul
        class="hidden justify-between pointer-events-auto md:flex"
      >
        <For each={NAV_LINKS}>
          {({ to, text }) => (
            <li>
              <A href={to}>
                <RollingText class="px-3">
                  {text}
                </RollingText>
              </A>
            </li>
          )}
        </For>
      </ul>

      {/* mobile menu */}
      <MobileMenu>
        <ul class="flex flex-col gap-4">
          <For each={NAV_LINKS}>
            {({ to, text }) => (
              <li>
                <A href={to}>{text}</A>
              </li>
            )}
          </For>
        </ul>
      </MobileMenu>
    </nav>
  );
};

// apps/next/components/Nav.tsx
import MobileMenu from "@/components/MobileMenu";
import RollingText from "@/components/RollingText";
import TransitionLink from "@/components/TransitionLink";

const NAV_LINKS = [
  {
    href: "/_/about",
    text: "About Us",
  },
  {
    href: "/_/animation",
    text: "Animation",
  },
  {
    href: "/_/components",
    text: "Components",
  },
  {
    href: "/_/webgl",
    text: "WebGl",
  },
  {
    href: "/_/data-loading",
    text: "Data",
  },
  {
    href: "/_/content",
    text: "CMS Content",
  },
];

export default function Nav() {
  return (
    <nav
      className="pointer-events-none fixed top-0 left-0 z-100 flex items-center justify-between px-gx py-6"
      style={{ width: "calc(100vw - var(--scrollbar-w, 0px))" }}
    >
      <TransitionLink
        aria-label="homepage"
        className="pointer-events-auto z-20"
        href="/"
      >
        <p>LOGO</p>
      </TransitionLink>

      <ul className="pointer-events-auto hidden justify-between md:flex">
        {NAV_LINKS.map(({ href, text }) => (
          <li key={href}>
            <TransitionLink href={href}>
              <RollingText className="px-3">{text}</RollingText>
            </TransitionLink>
          </li>
        ))}
      </ul>

      <MobileMenu>
        <ul className="flex flex-col gap-4">
          {NAV_LINKS.map(({ href, text }) => (
            <li key={href}>
              <TransitionLink href={href}>{text}</TransitionLink>
            </li>
          ))}
        </ul>
      </MobileMenu>
    </nav>
  );
}
