// packages/three/src/solid/Canvas.tsx
import { onCleanup, onMount } from "solid-js";
import { setGlContext } from "@local/gl-context";
import { Gl } from "../gl";
import type { SolidCanvasProps as CanvasProps } from "../canvasTypes";

export type { CanvasDeps, SolidCanvasProps } from "../canvasTypes";

export default function Canvas(props: CanvasProps) {
  const webgl = (el: HTMLDivElement) => {
    let clearGlContext: (() => void) | undefined;

    onMount(() => {
      clearGlContext = setGlContext(props.deps);
      Gl.start(el);
    });

    onCleanup(() => {
      Gl.destroy();
      props.deps.setWebgl?.({ loaded: false });
      clearGlContext?.();
    });
  };

  return (
    <div
      use:webgl
      class={props.class ?? "fixed inset-0 z-[-1] h-screen w-screen"}
    />
  );
}

// packages/three/src/react/Canvas.tsx
"use client";

import { useEffect, useRef } from "react";
import { setGlContext } from "@local/gl-context";
import { Gl } from "../gl";
import type { CanvasDeps } from "../canvasTypes";

export type { CanvasDeps } from "../canvasTypes";

export interface ReactCanvasProps {
  deps: CanvasDeps;
  className?: string;
}

/**
 * React equivalent of `@local/three/solid` Canvas: sets gl-context, mounts WebGL, tears down on unmount (HMR-safe).
 */
export default function Canvas({ deps, className }: ReactCanvasProps) {
  const ref = useRef<HTMLDivElement | null>(null);
  const depsRef = useRef(deps);
  depsRef.current = deps;

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const deps = depsRef.current;
    const clearGlContext = setGlContext(deps);
    Gl.start(el);

    return () => {
      Gl.destroy();
      deps.setWebgl?.({ loaded: false });
      clearGlContext();
    };
  }, []);

  return (
    <div
      ref={ref}
      className={className ?? "fixed inset-0 z-[-1] h-screen w-screen"}
    />
  );
}
