// packages/three/src/solid/useWebglNode.tsx
import { onMount, onCleanup, createSignal, createEffect } from "solid-js";
import { createVisibilityObserver } from "@solid-primitives/intersection-observer";

import { mountWebglNode } from "../core/mountWebglNode";

export const useWebglNode = (
	classToInstantiate: any,
	sceneToAttachTo: any = null,
) => {
	const vo = createVisibilityObserver({ threshold: 0 });

	const [ref, setRef] = createSignal<HTMLElement | null>(null);
	const [node, setNode] = createSignal<any>(null);

	let mounted: ReturnType<typeof mountWebglNode> | undefined;

	onMount(() => {
		if (!ref()) return;
		const r = ref()!;
		const visible = vo(r);

		mounted = mountWebglNode({
			el: r,
			classToInstantiate,
			attachTo: sceneToAttachTo,
			getInView: () => !!visible(),
			onNode: setNode,
		});

		createEffect(() => {
			mounted?.setInView(!!visible());
		});
	});

	onCleanup(() => {
		mounted?.dispose();
	});

	return { setRef, ref, node };
};

// packages/three/src/react/useWebglNode.ts
"use client";

import { useEffect, useRef, useState } from "react";

import { mountWebglNode } from "../core/mountWebglNode";
import type {
  WebglNodeConstructor,
  WebglNodeInstance,
} from "../core/mountWebglNode";

/**
 * React port of `@local/three/solid` `useWebglNode`: ref + visibility + dispose.
 */
export function useWebglNode(
  classToInstantiate: WebglNodeConstructor,
  sceneToAttachTo: object | null = null,
) {
  const ref = useRef<HTMLDivElement | null>(null);
  const nodeRef = useRef<WebglNodeInstance | undefined>(undefined);
  const [visible, setVisible] = useState(false);
  const visibleRef = useRef(visible);
  visibleRef.current = visible;

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const io = new IntersectionObserver(
      (entries) => {
        setVisible(entries[0]?.isIntersecting ?? false);
      },
      { threshold: 0 },
    );
    io.observe(el);

    const mounted = mountWebglNode({
      el,
      classToInstantiate,
      attachTo: sceneToAttachTo,
      getInView: () => visibleRef.current,
      onNode: (node) => {
        nodeRef.current = node;
      },
    });

    return () => {
      io.disconnect();
      mounted.dispose();
    };
  }, [classToInstantiate, sceneToAttachTo]);

  useEffect(() => {
    if (nodeRef.current) nodeRef.current.inView = visible;
  }, [visible]);

  return ref;
}
